---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - migrate.migrate.dev
  resources:
  - migrationplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migrate.migrate.dev
  resources:
  - migrationplans/finalizers
  verbs:
  - update
- apiGroups:
  - migrate.migrate.dev
  resources:
  - migrationplans/status
  verbs:
  - get
  - patch
  - update
