name: Docker Build & Publish

on:
  push:
    branches: ['main']
    tags: ['v*'] # also publish on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/openshift-to-cloud-operator:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/openshift-to-cloud-operator:${{ github.sha }}
